#  === redis config ===

CV_REDIS_HOST = '127.0.0.1'
CV_REDIS_PORT = 6379
CV_REDIS_DB = 2

# 患者类型 1=门诊,2=急诊,3=住院,4=体检

PATIENT_TYPE_OUTPATIENT_SERVICE = 1
PATIENT_TYPE_EMERGENCY_DEPARTMENT = 2
PATIENT_TYPE_HOSPITALIZATION = 3
PATIENT_TYPE_PHYSICAL_EXAMINATION = 4

# 危机值来源 1=人工 2=检验系统 3=影像系统

CV_SOURCE_LABOR = 1
CV_SOURCE_INSPECTION_SYSTEM = 2
CV_SOURCE_IMAGING_SYSTEM = 3

# cv state 危机值状态

INVALID_STATE = 0  # 作废
CREATED_STATE = 1   # 新建
NOTIFICATION_NURSE_STATE = 2  # 已通知护理
NURSE_RECV_TIMEOUT_STATE = 3   # 护理接收超时
NURSE_RECV_STATE = 4  # 护理已接收
NOTIFICATION_DOCTOR_STATE = 5  # 已通知医生
DOCTOR_RECV_TIMEOUT_STATE = 6  # 医生接收超时
DOCTOR_RECV_STATE = 7  # 医生已接收
DOCTOR_HANDLE_TIMEOUT_STATE = 8  # 医生处理超时
DOCTOR_HANDLE_STATE = 9  # 医生已处理


# cv timed task
WAIT_NURSE_RECV = 1
WAIT_NURSE_RECV_REDIS_KEY = 'CV_WAIT_NURSE_RECV'
WAIT_DOCTOR_RECV = 2
WAIT_DOCTOR_RECV_REDIS_KEY = 'CV_WAIT_DOCTOR_RECV'
WAIT_DOCTOR_HANDLE = 3
WAIT_DOCTOR_HANDLE_REDIS_KEY = 'CV_WAIT_DOCTOR_HANDLE'


# 超时时间 redis key
TIMEOUT_REDIS_KEY = {'nurse_recv': 'CV_NURSE_RECV_TIMEOUT',
                     'nurse_send': 'CV_NURSE_SEND_TIMEOUT',
                     'doctor_recv': 'CV_DOCTOR_RECV_TIMEOUT',
                     'doctor_handle': 'CV_DOCTOR_HANDLE_TIMEOUT',
                     'total': 'CV_TOTAL_TIMEOUT'}

# 部门信息
DEPT_INFO_REDIS_KEY = 'CV_DEPT_INFO_REDIS_KEY'

# 运行中的危机值列表
RUNNING_CVS_REDIS_KEY = 'CV_RUNNING_CVS'

# 站点类型
CV_SITES_REDIS_KEY = {1: 'CV_SITES_WARD_', 2: 'CV_SITES_DEPT_'}
